# Generated by Django 5.0 on 2023-12-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Contact',
        ),
    ]
